"""Protocol models for WikiArena v1 draft."""

from wikiarena.protocol.enums import (
    ErrorScope,
    LinkPolicy,
    NavigationBackend,
    ParticipantKind,
    PathKind,
    PathSource,
    RedirectPolicy,
    ResponseContract,
    RunEventType,
    RunStatus,
    SolverBackend,
    StepOutcome,
    TaskExecutionAnnotationStatus,
    TerminalOutcome,
    TerminationReason,
)
from wikiarena.protocol.errors import ErrorRecord
from wikiarena.protocol.events import EventEnvelope
from wikiarena.protocol.hashing import canonical_json, stable_sha256
from wikiarena.protocol.results import (
    BenchmarkResult,
    ModelCallMetrics,
    MoveRecord,
    RaceResult,
    RunResult,
    StepAttemptRecord,
    StepSolverMetrics,
    TaskExecutionAnnotation,
)
from wikiarena.protocol.rules import (
    BenchmarkRules,
    ExecutionPolicy,
    HarnessConfig,
    NavigationRules,
    ScoringRules,
)
from wikiarena.protocol.specs import (
    BenchmarkSpec,
    DriverConfig,
    ParticipantSpec,
    RaceSpec,
    RunSpec,
    SolverShortestPath,
    TaskSpec,
    build_task_id,
)
from wikiarena.protocol.version import DEFAULT_PROTOCOL_VERSION

__all__ = [
    "BenchmarkResult",
    "BenchmarkRules",
    "BenchmarkSpec",
    "DEFAULT_PROTOCOL_VERSION",
    "DriverConfig",
    "ErrorRecord",
    "ErrorScope",
    "EventEnvelope",
    "ExecutionPolicy",
    "HarnessConfig",
    "LinkPolicy",
    "ModelCallMetrics",
    "MoveRecord",
    "NavigationBackend",
    "NavigationRules",
    "ParticipantKind",
    "ParticipantSpec",
    "PathKind",
    "PathSource",
    "RaceResult",
    "RaceSpec",
    "RedirectPolicy",
    "ResponseContract",
    "RunEventType",
    "RunResult",
    "RunSpec",
    "RunStatus",
    "ScoringRules",
    "SolverBackend",
    "StepAttemptRecord",
    "StepOutcome",
    "StepSolverMetrics",
    "SolverShortestPath",
    "TaskSpec",
    "TaskExecutionAnnotation",
    "TaskExecutionAnnotationStatus",
    "TerminalOutcome",
    "TerminationReason",
    "build_task_id",
    "canonical_json",
    "stable_sha256",
]
